package me.richter.commandsAndGUI.module.utils

object LegacyColorCodesToMiniMassageTags {
	fun mach(legacyString: String): String {
		return legacyString
			.replace("§0", "<#000000>")
			.replace("§1", "<#0000AA>")
			.replace("§2", "<#00AA00>")
			.replace("§3", "<#00AAAA>")
			.replace("§4", "<#AA0000>")
			.replace("§5", "<#AA00AA>")
			.replace("§6", "<#FFAA00>")
			.replace("§7", "<#AAAAAA>")
			.replace("§8", "<#555555>")
			.replace("§9", "<#5555FF>")
			.replace("§a", "<#55FF55>")
			.replace("§b", "<#55FFFF>")
			.replace("§c", "<#FF5555>")
			.replace("§d", "<#FF55FF>")
			.replace("§e", "<#FFFF55>")
			.replace("§f", "<#FFFFFF>")
			.replace("§k", "<obfuscated>")
			.replace("§l", "<bold>")
			.replace("§m", "<strikethrough>")
			.replace("§n", "<underlined>")
			.replace("§o", "<italic>")
			.replace("§r", "<reset>")
			.replace("&0", "<#000000>")
			.replace("&1", "<#0000AA>")
			.replace("&2", "<#00AA00>")
			.replace("&3", "<#00AAAA>")
			.replace("&4", "<#AA0000>")
			.replace("&5", "<#AA00AA>")
			.replace("&6", "<#FFAA00>")
			.replace("&7", "<#AAAAAA>")
			.replace("&8", "<#555555>")
			.replace("&9", "<#5555FF>")
			.replace("&a", "<#55FF55>")
			.replace("&b", "<#55FFFF>")
			.replace("&c", "<#FF5555>")
			.replace("&d", "<#FF55FF>")
			.replace("&e", "<#FFFF55>")
			.replace("&f", "<#FFFFFF>")
			.replace("&k", "<obfuscated>")
			.replace("&l", "<bold>")
			.replace("&m", "<strikethrough>")
			.replace("&n", "<underlined>")
			.replace("&o", "<italic>")
			.replace("&r", "<reset>")
	}
}