#Enables/Disables specific modules of the plugin
Modules:
  BackpackModule: true
  FlyModule: true
  GodmodeModule: true
  GuiModule: true
  InvViewModule: true
  WorldManager: true
  VanishModule: true
  JumpModule: true
  HealModule: true
  SetupCommand: true
  Scoreboard: false

#Which workstations can be accessed using the gui or the command
Workstations:
  All: true
  Workbench: true
  Enchanting: true
  Stonecutter: true
  CartographyTable: true
  Anvil: true
  SmithingTable: true
  Grindstone: true
  Loom: true
  Furnace: true
  BlastFurnace: true
  Creative: true
  Brewing: true
  Crafting: true
  Smoker: true
