name: CommandsAndGUI
version: '${project.version}'
main: me.richter.commandsAndGUI.Main
api-version: '1.20'

commands:
  setup:
    description: Executes the Setup Commands
    permission: commandsAndGUI.setup

  gui:
    description: opens a gui
    permission: commandsAndGUI.gui

  worldManager:
    permission: commandsAndGUI.worldManager

  jump:
    description: JUMP!
    permission: commandsAndGUI.jump

  god:
    permission: commandsAndGUI.god

  vanish:
    permission: commandsAndGUI.vanish

  fly:
    description: Toggle flight
    permission: commandsAndGUI.fly
    permission-message: You do not have the permission to execute this command (you need the "fly" permission)
    ##aliases:
    ##  - toggleflight
    ##  - togglefly
    ##  - f

  workstation:
    permission: commandsAndGUI.dev

  backpack:
    permission: commandsAndGUI.backpack

  sit:
    description: is nen bissel broken, muss fixen
    permission: commandsAndGUI.sit