name: CommandsAndGUI
version: '1.21'
main: me.richter.commandsAndGUI.Main
api-version: '1.21'
softdepend: ["PlaceholderAPI"]

commands:
  backpack:
    description: create, share, and use double chest sized backpacks
    usage: digga schau halt ma die tab vorschläge an (viel zu faul die ganzen möglichkeiten hier hin zu schallern)
    aliases: []
    permission: commandsAndGUI.command.backpack
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.backpack permission)

  fly:
    description: allows you to fly or change the fly speed
    usage: /<command> [speed/on/off] [speed 0-10]
    aliases: []
    permission: commandsAndGUI.command.fly
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.fly permission)

  god:
    description: makes you invincible
    usage: /<command> [playerName]
    aliases: []
    permission: commandsAndGUI.command.god
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.god permission)

  commandsandgui:
    description: opens the GUI of CommandAndGUI
    usage: /<command>
    aliases: ["cag"]
    permission: commandsAndGUI.command.gui
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.gui permission)

  gui:
    description: opens the GUI of CommandAndGUI
    usage: /<command>
    aliases: []
    permission: commandsAndGUI.command.gui
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.gui permission)

  invSee:
    description: opens the Inventory Viewer GUI of CommandAndGUI
    usage: /<command> [targetPlayer]
    aliases: [ ]
    permission: commandsAndGUI.command.invSee
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.invSee permission)

  heal:
    description: heal a player
    usage: /<command> [playerName]
    aliases: []
    permission: commandsAndGUI.command.heal
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.heal permission)

  jump:
    description: make a player jump high
    usage: /<command> [playerName]
    aliases: []
    permission: commandsAndGUI.command.jump
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.jump permission)

  setup:
    description: Executes the Setup Commands
    usage: /<command>
    aliases: []
    permission: commandsAndGUI.command.setup
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.setup permission)

  sit:
    description: is nen bissel broken, muss fixen, aber man kann sich setzen (wer hätte das gedacht)
    usage: /<command>
    aliases: []
    permission: commandsAndGUI.command.sit
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.sit permission)

  vanish:
    description: makes you invisible to other players
    usage: /<command> [fakeDisconnect]
    aliases: []
    permission: commandsAndGUI.command.vanish
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.vanish permission)

  workstation:
    description: opens a workstation like the crafting menu
    usage: /<command> [workstation]
    aliases: []
    permission: commandsAndGUI.command.dev
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.dev permission)

  worldManager:
    description: is nen bissel SEHR broken, einfach nicht nutzen
    usage: just dont
    aliases: []
    permission: commandsAndGUI.command.worldManager
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.worldManager permission)

  getItem:
    description: get an item from the plugin
    usage: /<command> [item]
    aliases: []
    permission: commandsAndGUI.command.getItem
    permission-message: You do not have permission to use this command (you need the commandsAndGUI.command.getItem permission)

  getHead:
    description: gives head
    usage: /<command> [a minecraft texture url (textures.minecraft.net/texture/)]

  timer:
    description: timer
    usage: /<command> resume, /<command> pause, /<command> set [zeit], /<command> reset

  countdown:
    description: countdown

  testScoreboard:
    description: maaaaan ich kann das alles nicht mehr, ich muss noch nen schulprojekt machen :(

  track:
    description: track a person using a compass





permissions:
  commandsAndGUI.world.break:
    default: true